version: '3.5'
services:
  server:
    build:
      context: .
      dockerfile: ./Dockerfile
      target: build
    command: start
    environment:
      - PORT=8081
    volumes:
      - ./src:/opt/src
    ports:
      - "8081:8081"
      - "9229:9229"

  proxy:
    image: caddy/caddy:alpine
    volumes:
      - ./caddyfile:/etc/caddy/Caddyfile
      - ./files:/files
    ports:
      - '443:443'
      - "8080:80"
